$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: {{DEPLOYMENT_NAME}}
endpoint_name: octoml-triton-endpoint
model: 
  path: ./models/{{MODEL_NAME_}} # Local models
model_mount_path: /models # Container model registry
environment: 
  name: octoml-model-dep-test
  image: {{ACR_IMG_NAME}} #need to update

  inference_config:
      liveness_route:
          path: /v2/health/live
          port: 8000
      readiness_route:
          path: /v2/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: {{INSTANCE_TYPE}}
instance_count: 1