$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: octoml-resnet50-dep-5
endpoint_name: octoml-triton-endpoint
model: 
  path: ./models/resnet50_v1_12 # Local models
model_mount_path: /models # Container model registry
environment: 
  name: az-triton-test-env
  image: {{ACR_IMG_NAME}} #need to update

  inference_config:
      liveness_route:
          path: /v2/health/live
          port: 8000
      readiness_route:
          path: /v2/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: Standard_DS4_v2
instance_count: 1